

Scale: 1 
#257.9 / (620.133-214.067)
Pythagoras: True
Gridsize: 100
CLim Heatmap: [0, 10]
Colormap: afmhot
Ignore Buildup: False
Multiple CPU: False

Isocontours:
  Values: [0.1, 0.3, 1, 2.5, 5 ,10]
  Colors: ['b', 'g', 'y', 'r', 'c', 'm']

Files:
  Sources:  example/sources.yml
  Shielding: example/shielding.yml
  Floor plan: example/floor_plan.png

Show:
  All sources: True
  Sum sources: True
 
Export:
  Export directory: 'Example\'
  All sources: True
  Sum sources: True
  File type: .png
  DPI: 300
  
  