# WARNING DO NOT ADD OR REMOVE ENTRIES. TO USE YOUR OWN CONFIGURATION PLEASE
# RUN: pyshield.run(config=my_config.yml)

log: 'debug'               # set to debug or info

# =============================================================================
# Floor plan
# =============================================================================
floor_plan: floor_plan.png  # Floor plan of the room/facility
scale: 1                    # scale of floor plan in cm/pixels
origin: [0, 0]              # arbritrary origin in floor plan in cm
 
#==============================================================================
# Calculations options
#==============================================================================
intersection_thickness: True  # calculate effective barrier thickness for oblique intersections
disable_buildup: False        # if True buildup is set 1 for all calculations
multi_cpu: True               # Divide workload over the available CPU cores
grid_size: 10                 # grid spacing for cartesian grid or radial sampling for polor grid
number_of_angles: 90          # angles used for sampling polar grid
grid: polar                   # cartesian or polar grid
calculate:                    # calculate on grid or specified points, both or none
  - grid
  - points


#==============================================================================
#  Input and output for calculations
#==============================================================================

# files are found in the current working directory. Files are loaded if they
# are found in the specified path. By default the following files will be
# tried from the local working directory

barriers: barriers.yml      # barrier definitions
points: points.yml          # dose points definitions
sources: sources.yml        # source definitions


# simulate a floor by specifying this as a barrier
# e.g. floor:
#        Concrete: 20
#  Simunlates a 20 cm concrete floor by adding 20cm concrete around each source
floor: {}

height: 0  # Use in conjuction with floor, this specifies the distance to the other
# floor from the source. Distance will be corrected 

#==============================================================================
#  Display options
#==============================================================================
 
    
# sum_sources: Show a dose map of the summed contributions of all sources
# all_sources: Show a dose map of each individual source
# sources: Show the floorplan with labels for each source
# points: Show the floorplan with a label next to each dose point
# floor_plan: Show the floor_plan with barriers
# sum_table: display formatted table in (i)python console
show: ['sum_sources', 'floor_plan', 'sources', 'points', 'sum_table']



#==============================================================================
# Export options
#==============================================================================

# Files are saved in the current working directory
export_excel: True
export_images: True
export_dir: './output/'
excel_filename: result.xlsx


# resources, physics data used in calculations
attenuation: $pyshield_folder$/physics/attenuation.xlsx
buildup: $pyshield_folder$/physics/buildup.xlsx
isotopes: $pyshield_folder$/physics/isotopes.yml
materials: $pyshield_folder$/physics/materials.yml

# display settings
visualization: $pyshield_folder$/visualization.yml