# input dict or yml file

log: 'debug'               # set to debug or info

#==============================================================================
# Calculations options
#==============================================================================
pythagoras: True          # True or False
disable_buildup: False    # if True buildup is set 1 for all calculations
multi_cpu: True           # Divide workload over the available CPU cores
grid_size: 10             # grid spacing for cartesian grid or radial sampling for polor grid
number_of_angles: 90      # angles used for sampling polar grid
grid: polar               # cartesian or polar grid
calculate:                # calculate on grid or specified points or both
  - grid
  - points
scale: 1                  # scale of floor plan in cm/pixels
origin:                   # arbritrary origin in floor plan in cm
 - 0
 - 0

#==============================================================================
#  Input and output for calculations
#==============================================================================

# files are found in the current working directory. Files are loaded if they
# are found in the specified path. By default the following files will be
# tried from the local working directory

barriers: barriers.yml      # barrier definitions
points: points.yml          # dose points definitions
sources: sources.yml        # source definitions


# simulate a floor by specifying this as a barrier
# e.g. floor:
#        Concrete: 20
#  Simunlates a 20 cm concrete floor
floor: {}

height: 0  # Use in conjuction with floor, this specifies the distance to the other
# floor from the source

export_dir: './output/'

#==============================================================================
#  Display options
#==============================================================================
clim_heatmap:             # Limits for the colorscale of the heatmap in mSv
  - 0
  - 10
colormap: afmhot          # colormap for heatmap

isocontour_lines:         # mSv vs any valid matplotlib color
  0.1: lightgreen
  0.3: darkgreen
  0.4: lightblue
  1.2: darkblue
  1.67: red
  4: darkred
  5: magenta
  12: darkmagenta

# sum_sources: Show a dose map of the summed contributions of all sources
# all_sources: Show a dose map of each individual source
# sources: Show the floorplan with labels for each source
# points: Show the floorplan with a label next to each dose point
# floor_plan: Show the floor_plan with barriers
# sum_table: display formatted table in (i)python console
show: ['sum_sources', 'floor_plan', 'sources', 'points', 'sum_table']

material_colors: colors.yml # File that specifies the colors for the barriers
floor_plan: floor_plan.png  # Floor plan of the room/facility

#==============================================================================
# Export options
#==============================================================================

# Files are saved in the current working directory
export_excel: True
export_images: True
excel_filename_summary: summed_result.xlsx
excel_filename_fullresult: full_result.xlsx
